//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class insp_whse
    {
        public int whse_id { get; set; }
        public int insp_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string gencarton1_result { get; set; }
        public string gencarton1_text { get; set; }
        public string gencarton2_result { get; set; }
        public string gencarton2_text { get; set; }
        public string gencarton3_result { get; set; }
        public string gencarton3_text { get; set; }
        public string gencarton4_result { get; set; }
        public string gencarton4_text { get; set; }
        public string gencarton5_result { get; set; }
        public string gencarton5_text { get; set; }
        public string outcarton1_result { get; set; }
        public string outcarton1_text { get; set; }
        public string outcarton2_result { get; set; }
        public string outcarton2_text { get; set; }
        public string outcarton3_result { get; set; }
        public string outcarton3_text { get; set; }
        public string outcarton4_result { get; set; }
        public string outcarton4_text { get; set; }
        public string outcarton5_result { get; set; }
        public string outcarton5_text { get; set; }
        public string outcarton6_result { get; set; }
        public string outcarton6_text { get; set; }
        public string outcarton7_result { get; set; }
        public string outcarton7_text { get; set; }
        public Nullable<bool> is_complete { get; set; }
    
        public virtual insp_head insp_head { get; set; }
    }
}
