//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class insp_head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insp_head()
        {
            this.insp_detail = new HashSet<insp_detail>();
            this.insp_whse = new HashSet<insp_whse>();
        }
    
        public int insp_id { get; set; }
        public Nullable<System.DateTime> insp_date { get; set; }
        public string customer_name { get; set; }
        public string customer_uid { get; set; }
        public string customer_po { get; set; }
        public string vendor_name { get; set; }
        public string vendor_uid { get; set; }
        public string vendor_po { get; set; }
        public string vendor_po_uid { get; set; }
        public string ordernumber_sales { get; set; }
        public string orderid_sales { get; set; }
        public string sales_email { get; set; }
        public string username { get; set; }
        public string packaging { get; set; }
        public string manufacturer { get; set; }
        public string fullpartnumber { get; set; }
        public Nullable<int> quantity { get; set; }
        public string date_code { get; set; }
        public string lot { get; set; }
        public string coo { get; set; }
        public string package_type { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string inspector { get; set; }
        public string inspector_uid { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<bool> is_complete { get; set; }
        public Nullable<System.DateTime> expectedShipDate { get; set; }
        public string result { get; set; }
        public string resultnotes { get; set; }
        public string completed_by { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string status { get; set; }
        public Nullable<bool> is_insp_complete { get; set; }
        public Nullable<bool> email_sent { get; set; }
        public string orddet_line_uid { get; set; }
        public bool is_demo { get; set; }
        public Nullable<int> source_insp_id { get; set; }
        public Nullable<bool> final_InspectionComplete { get; set; }
        public Nullable<System.DateTime> final_InspectionCompleteDate { get; set; }
        public string final_Inspector { get; set; }
        public string final_Inspector_uid { get; set; }
        public string current_turn_back_id { get; set; }
        public Nullable<bool> initial_alert_sent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insp_detail> insp_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insp_whse> insp_whse { get; set; }
    }
}
