//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class insp_images
    {
        public int unique_id { get; set; }
        public string img_name { get; set; }
        public string img_type { get; set; }
        public byte[] img_blob { get; set; }
        public string img_description { get; set; }
        public int insp_id { get; set; }
        public string insp_section_id { get; set; }
        public string insp_image_id { get; set; }
        public string orderid_purchase { get; set; }
        public string orderid_sales { get; set; }
        public string partrecord_uid { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string insp_type { get; set; }
        public string img_path { get; set; }
        public string img_path_web { get; set; }
    }
}
