//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class insp_detail
    {
        public int detail_id { get; set; }
        public int insp_id { get; set; }
        public string inner_cont1_result { get; set; }
        public string inner_cont1_text { get; set; }
        public string inner_cont2_result { get; set; }
        public string inner_cont2_text { get; set; }
        public string inner_cont3_result { get; set; }
        public string inner_cont3_text { get; set; }
        public string inner_cont4_result { get; set; }
        public string inner_cont4_text { get; set; }
        public string inner_cont5_result { get; set; }
        public string inner_cont5_text { get; set; }
        public string inner_cont6_result { get; set; }
        public string inner_cont6_text { get; set; }
        public string inner_cont7_result { get; set; }
        public string inner_cont7_text { get; set; }
        public string tube1_result { get; set; }
        public string tube1_text { get; set; }
        public string tube2_result { get; set; }
        public string tube2_text { get; set; }
        public string tube3_result { get; set; }
        public string tube3_text { get; set; }
        public string tube4_result { get; set; }
        public string tube4_text { get; set; }
        public string tube5_result { get; set; }
        public string tube5_text { get; set; }
        public string reel1_result { get; set; }
        public string reel1_text { get; set; }
        public string reel2_result { get; set; }
        public string reel2_text { get; set; }
        public string reel3_result { get; set; }
        public string reel3_text { get; set; }
        public string reel4_result { get; set; }
        public string reel4_text { get; set; }
        public string reel5_result { get; set; }
        public string reel5_text { get; set; }
        public string reel6_result { get; set; }
        public string reel6_text { get; set; }
        public string reel7_result { get; set; }
        public string reel7_text { get; set; }
        public string tray1_result { get; set; }
        public string tray1_text { get; set; }
        public string tray2_result { get; set; }
        public string tray2_text { get; set; }
        public string tray3_result { get; set; }
        public string tray3_text { get; set; }
        public string tray4_result { get; set; }
        public string tray4_text { get; set; }
        public string tray5_result { get; set; }
        public string tray5_text { get; set; }
        public string tray6_result { get; set; }
        public string tray6_text { get; set; }
        public string bulk1_result { get; set; }
        public string bulk1_text { get; set; }
        public string bulk2_result { get; set; }
        public string bulk2_text { get; set; }
        public string bulk3_result { get; set; }
        public string bulk3_text { get; set; }
        public string bulk4_result { get; set; }
        public string bulk4_text { get; set; }
        public string initial1_result { get; set; }
        public string initial1_text { get; set; }
        public string initial2_result { get; set; }
        public string initial2_text { get; set; }
        public string initial3_result { get; set; }
        public string initial3_text { get; set; }
        public string initial4_result { get; set; }
        public string initial4_text { get; set; }
        public string initial5_result { get; set; }
        public string initial5_text { get; set; }
        public string initial6_result { get; set; }
        public string initial6_text { get; set; }
        public string initial7_result { get; set; }
        public string initial7_text { get; set; }
        public string detail1_result { get; set; }
        public string detail1_text { get; set; }
        public string detail2_result { get; set; }
        public string detail2_text { get; set; }
        public string detail3_result { get; set; }
        public string detail3_text { get; set; }
        public string detail4_result { get; set; }
        public string detail4_text { get; set; }
        public string detail5_result { get; set; }
        public string detail5_text { get; set; }
        public string detail6_result { get; set; }
        public string detail6_text { get; set; }
        public string detail7_result { get; set; }
        public string detail7_text { get; set; }
        public string detail8_result { get; set; }
        public string detail8_text { get; set; }
        public string detail9_result { get; set; }
        public string detail9_text { get; set; }
        public string detail10_result { get; set; }
        public string detail10_text { get; set; }
        public string detail11_result { get; set; }
        public string detail11_text { get; set; }
        public string detail12_result { get; set; }
        public string detail12_text { get; set; }
        public string detail13_result { get; set; }
        public string detail13_text { get; set; }
        public string detail14_result { get; set; }
        public string detail14_text { get; set; }
        public string detail15_result { get; set; }
        public string detail15_text { get; set; }
        public string detail16_result { get; set; }
        public string detail16_text { get; set; }
        public string detail17_result { get; set; }
        public string detail17_text { get; set; }
        public Nullable<bool> is_solvent { get; set; }
        public string solvent1_result { get; set; }
        public string solvent1_text { get; set; }
        public string solvent2_result { get; set; }
        public string solvent2_text { get; set; }
        public string solvent3_result { get; set; }
        public string solvent3_text { get; set; }
        public Nullable<bool> is_mech { get; set; }
        public string mech1_result { get; set; }
        public string mech1_text { get; set; }
        public string mech2_result { get; set; }
        public string mech2_text { get; set; }
        public string mech3_result { get; set; }
        public string mech3_text { get; set; }
        public Nullable<bool> is_tube { get; set; }
        public Nullable<bool> is_reel { get; set; }
        public Nullable<bool> is_tray { get; set; }
        public Nullable<bool> is_bulk { get; set; }
        public byte[] imagetest1 { get; set; }
        public string imagetest2 { get; set; }
        public Nullable<bool> is_complete { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<bool> is_addtesting { get; set; }
        public string addtesting_text { get; set; }
    
        public virtual insp_head insp_head { get; set; }
    }
}
