//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonCon_Disposition
    {
        public int DispositionID { get; set; }
        public int NonConID { get; set; }
        public Nullable<bool> as_is { get; set; }
        public Nullable<bool> replace { get; set; }
        public string vendor_return { get; set; }
        public Nullable<bool> return_to_stock { get; set; }
        public Nullable<bool> quarantined { get; set; }
        public Nullable<bool> scrap { get; set; }
        public string containment_notes { get; set; }
        public string remarks { get; set; }
        public string submittedBy { get; set; }
        public System.DateTime dateSubmitted { get; set; }
        public Nullable<bool> dispositionComplete { get; set; }
        public string completedBy { get; set; }
    
        public virtual NonCon_Head NonCon_Head { get; set; }
    }
}
