//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonCon_RMA
    {
        public int NonConID { get; set; }
        public int RMAID { get; set; }
        public Nullable<bool> isVRMA { get; set; }
        public Nullable<bool> isCRMA { get; set; }
        public System.DateTime dateSubmitted { get; set; }
        public string submittedBy { get; set; }
        public Nullable<bool> isFunctionalIssue { get; set; }
        public Nullable<bool> fnSolderFail { get; set; }
        public Nullable<bool> fnElecFail { get; set; }
        public Nullable<bool> fnCoplanFail { get; set; }
        public Nullable<bool> fnProgramFail { get; set; }
        public string fnRemarks { get; set; }
        public Nullable<bool> isSuspectCounterfeit { get; set; }
        public Nullable<bool> scSecondaryCoating { get; set; }
        public Nullable<bool> scRemarked { get; set; }
        public Nullable<bool> scRefurb { get; set; }
        public Nullable<bool> scPulls { get; set; }
        public Nullable<bool> scCloned { get; set; }
        public string scRemarks { get; set; }
        public Nullable<bool> isDamaged { get; set; }
        public Nullable<bool> dmCarrier { get; set; }
        public Nullable<bool> dmSMCReceipt { get; set; }
        public Nullable<bool> dmCustReceipt { get; set; }
        public Nullable<bool> dmSMCWarehouse { get; set; }
        public Nullable<bool> dmProduct { get; set; }
        public Nullable<bool> dmPackage { get; set; }
        public string dmRemarks { get; set; }
        public Nullable<bool> isClerical { get; set; }
        public Nullable<bool> clSMC { get; set; }
        public Nullable<bool> clVendor { get; set; }
        public Nullable<bool> clCustomer { get; set; }
        public string clRemarks { get; set; }
        public Nullable<bool> isImproperPKG { get; set; }
        public Nullable<bool> ipContainer { get; set; }
        public Nullable<bool> ipMSL { get; set; }
        public Nullable<bool> ipESD { get; set; }
        public Nullable<bool> ipTandR { get; set; }
        public string ipRemarks { get; set; }
        public string RMARemarks { get; set; }
        public Nullable<bool> RMAComplete { get; set; }
        public string completedBy { get; set; }
        public Nullable<int> VRMAQTY { get; set; }
        public Nullable<int> CRMAQTY { get; set; }
        public string paymentType { get; set; }
    
        public virtual NonCon_Head NonCon_Head { get; set; }
    }
}
