//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonCon_Customer
    {
        public int NonConCustomerID { get; set; }
        public int NonConID { get; set; }
        public string customerPO { get; set; }
        public string customerPOID { get; set; }
        public string SONumber { get; set; }
        public string SONumberUID { get; set; }
        public string CustomerUID { get; set; }
        public string customerName { get; set; }
        public string sellerEmail { get; set; }
        public string sellerName { get; set; }
        public System.DateTime dateSubmitted { get; set; }
        public string submittedBy { get; set; }
    
        public virtual NonCon_Head NonCon_Head { get; set; }
    }
}
