//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonCon_Payment
    {
        public int PaymentID { get; set; }
        public int NonConID { get; set; }
        public string confirmedNetProfit { get; set; }
        public Nullable<bool> isPaymentDue { get; set; }
        public Nullable<bool> isPaymentRefunded { get; set; }
        public Nullable<System.DateTime> dateRefunded { get; set; }
        public Nullable<bool> wirePaymentReceivedQB { get; set; }
        public Nullable<bool> checkCancelledQB { get; set; }
        public string checkNumber { get; set; }
        public Nullable<bool> creditPaymentReceivedQB { get; set; }
        public Nullable<bool> vendorCreditReceivedQB { get; set; }
        public string vendorCreditAmount { get; set; }
        public string submittedBy { get; set; }
        public System.DateTime dateSubmitted { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isPoorQuality { get; set; }
        public Nullable<bool> isSuspectCounterfeit { get; set; }
        public Nullable<bool> isDamaged { get; set; }
        public Nullable<bool> isClerical { get; set; }
        public Nullable<bool> isCustomerSpecific { get; set; }
        public Nullable<bool> paymentComplete { get; set; }
        public Nullable<bool> completedBy { get; set; }
        public string paypalNetAmnt { get; set; }
        public string paymentType { get; set; }
    
        public virtual NonCon_Head NonCon_Head { get; set; }
    }
}
