//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensibleDAL.ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sm_nonconEntities : DbContext
    {
        public sm_nonconEntities()
            : base("name=sm_nonconEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NonCon_Customer> NonCon_Customer { get; set; }
        public virtual DbSet<NonCon_Details> NonCon_Details { get; set; }
        public virtual DbSet<NonCon_Disposition> NonCon_Disposition { get; set; }
        public virtual DbSet<NonCon_Head> NonCon_Head { get; set; }
        public virtual DbSet<NonCon_Payment> NonCon_Payment { get; set; }
        public virtual DbSet<NonCon_RMA> NonCon_RMA { get; set; }
    }
}
