<?xml version="1.0" encoding="utf-8"?><Database Name="SeriLog" Class="SeriLogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=rz.sensiblemicro.local\SQLEXPRESS;Initial Catalog=SeriLog;Integrated Security=True" SettingsObjectName="SensibleDAL.Properties.Settings" SettingsPropertyName="SeriLogConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MessageTemplate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Exception" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Properties" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>